import {
  CATEGORY_PRESETS,
  ENGINE_VERSION,
  PRESET_VERSION,
  STATUTORY,
  catchmentPercentile,
  compareLocations,
  formatCurrency,
  formatNumber,
  formatPercent,
  resolveRent,
  rentSensitivity,
  scoreLocation,
  simulate,
  type BusinessCategory,
  type ComparedLocation,
  type Comparison,
  type CompetitorSummary,
  type CompetitorWithDistance,
  type DensityBand,
  type LatLng,
  type LocationScore,
  type RentSensitivity,
  type ResolvedRent,
  type ScenarioInputs,
  type SimulationResult,
} from "@spotential/sim-engine";

/**
 * Report view models — Feature 4.
 *
 * PURE. Every number in a PDF is produced here, by the SAME engine the browser
 * runs, and nothing derivable is ever taken from the request body. A client
 * that posts its own `score` gets it ignored, not honoured — otherwise the PDF
 * could disagree with the screen that produced it, and the PDF is the copy
 * that gets forwarded to a landlord or a bank.
 *
 * Split out from the template so the figures can be pinned with golden vectors
 * without rendering a byte of PDF.
 */

export interface Figure {
  label: string;
  value: string;
  note?: string;
}

export interface Row {
  cells: string[];
  emphasis?: boolean;
}

export interface Table {
  title: string;
  head: string[];
  rows: Row[];
  note?: string;
}

/** A dimension of the success score, ready to draw and to tabulate. */
export interface RadarSeries {
  label: string;
  /** One value per axis, 0..100. Unavailable axes are 0 and flagged below. */
  values: number[];
  /** Parallel to `values` — true where the dimension had no data. */
  missing: boolean[];
}

/** One distance ring, ready to draw. See `distanceBars`. */
export interface DistanceBand {
  label: string;
  value: number;
  unsearched: boolean;
}

/** A score dimension, ready to draw as a horizontal bar. */
export interface DimensionBar {
  label: string;
  score: number | null;
  basis: string;
}

export interface ReportModel {
  kind: "scenario" | "location" | "comparison";
  title: string;
  subtitle: string;
  /** ISO date the report was generated. */
  generatedOn: string;
  /**
   * The short version, in two or three sentences.
   *
   * DERIVED FROM THE SCORE OBJECT, never written by a model. It sits on the
   * cover, above the tables it summarises, and a generated sentence there
   * could contradict the numbers on the page behind it — the single failure
   * this product is built to avoid. Same rule as the on-screen Verdict.
   */
  summary: string[];
  figures: Figure[];
  tables: Table[];
  /** Distance rings for the competition chart. Empty outside location reports. */
  distanceBands: DistanceBand[];
  /** Score dimensions as bars. Empty outside location reports. */
  dimensionBars: DimensionBar[];
  /** Age profile for the demographics chart. Empty when unknown. */
  ageBands: { label: string; value: number }[];
  /** Radar axes, shared by every series. Empty for the scenario report. */
  radarAxes: string[];
  radarSeries: RadarSeries[];
  /** Month-by-month cash, for the cash-curve chart. Empty outside the scenario report. */
  cashCurve: number[];
  /** Static map, already fetched and inlined. Null when unavailable. */
  mapDataUri: string | null;
  mapNote: string | null;
  /** Sentences that must survive being forwarded. */
  disclosures: string[];
  engineVersion: string;
  presetVersion: string;
}

const today = (): string => new Date().toISOString().slice(0, 10);

/** Caveats every report carries, whatever its kind. */
function baseDisclosures(): string[] {
  return [
    `Generated by Spotential on ${today()}. Engine ${ENGINE_VERSION}, presets ${PRESET_VERSION}.`,
    "Figures are projections from the inputs shown, not a forecast and not advice. " +
      "Nothing here has been validated against real business outcomes.",
    `Statutory rates reviewed ${STATUTORY.reviewed}: EPF employer ${formatPercent(
      STATUTORY.epf.employerRateAtOrBelowTier,
      0,
    )} at or below RM${formatNumber(STATUTORY.epf.tierWage)} monthly wage and ${formatPercent(
      STATUTORY.epf.employerRateAboveTier,
      0,
    )} above it, SOCSO ${formatPercent(STATUTORY.socso.employerRate, 2)} and EIS ${formatPercent(
      STATUTORY.eis.employerRate,
      1,
    )} both capped at RM${formatNumber(STATUTORY.socso.wageCeiling)}, service tax ${formatPercent(
      STATUTORY.serviceTax.rate,
      0,
    )} on dine-in revenue above RM${formatNumber(
      STATUTORY.serviceTax.registrationThresholdAnnual,
    )} annual turnover.`,
    "Confirm every statutory rate against KWSP, PERKESO and RMCD before relying on it.",
  ];
}

// ---------------------------------------------------------------- scenario

export function buildScenarioReport(
  inputs: ScenarioInputs,
  map: { dataUri: string | null; note: string | null } = { dataUri: null, note: null },
): ReportModel {
  const result: SimulationResult = simulate(inputs);
  const category = CATEGORY_PRESETS[inputs.businessCategory];
  const { steady, breakEven, cash, derived } = result;

  const figures: Figure[] = [
    { label: "Monthly revenue", value: formatCurrency(steady.revenue), note: "at maturity" },
    { label: "Monthly expenses", value: formatCurrency(steady.totalExpenses) },
    {
      label: "Monthly profit",
      value: formatCurrency(steady.profit),
      note: `${formatPercent(steady.revenue > 0 ? steady.profit / steady.revenue : 0, 1)} margin`,
    },
    {
      label: "Payback",
      value: breakEven.paybackMonth === null ? "Not within 24 months" : `Month ${breakEven.paybackMonth}`,
      ...(breakEven.paybackBandLow !== null && breakEven.paybackBandHigh !== null
        ? { note: `range ${breakEven.paybackBandLow} to ${breakEven.paybackBandHigh}` }
        : {}),
    },
  ];

  const costRows: Row[] = result.costBreakdown.map((line) => ({
    cells: [line.key, formatCurrency(line.amount), formatPercent(line.pctOfRevenue, 1)],
  }));
  costRows.push({
    cells: ["Total", formatCurrency(steady.totalExpenses), ""],
    emphasis: true,
  });

  const tables: Table[] = [
    {
      title: "Assumptions",
      head: ["Input", "Value"],
      rows: [
        { cells: ["Business type", category.label] },
        { cells: ["Monthly rent", formatCurrency(inputs.monthlyRent)] },
        { cells: ["Initial investment", formatCurrency(inputs.initialInvestment)] },
        { cells: ["Deposit", `${inputs.securityDepositMonths} months`] },
        { cells: ["Average spend", formatCurrency(inputs.avgPricePerTransaction)] },
        { cells: ["Customers per day", formatNumber(inputs.customersPerDay)] },
        { cells: ["Trading days per month", formatNumber(derived.tradingDaysPerMonth, 2)] },
        { cells: ["Staff", `${formatNumber(inputs.staffCount)} at ${formatCurrency(inputs.avgMonthlyWage)}`] },
        { cells: ["Cost of goods", formatPercent(inputs.cogsPct, 0)] },
        { cells: ["Months to maturity", formatNumber(inputs.monthsToMaturity)] },
      ],
      note: category.source,
    },
    {
      title: "Monthly costs at maturity",
      head: ["Line", "Amount", "% of revenue"],
      rows: costRows,
    },
    {
      title: "Break-even and cash",
      head: ["Measure", "Value"],
      rows: [
        {
          cells: [
            "Operating break-even",
            breakEven.operatingTransactionsPerDay === null
              ? "Unreachable at any volume"
              : `${formatNumber(breakEven.operatingTransactionsPerDay)} customers/day`,
          ],
        },
        {
          cells: [
            "Cash break-even",
            breakEven.cashBreakEvenMonth === null
              ? "Not within 24 months"
              : `Month ${breakEven.cashBreakEvenMonth}`,
          ],
        },
        {
          cells: [
            "Investment payback",
            breakEven.paybackMonth === null ? "Not within 24 months" : `Month ${breakEven.paybackMonth}`,
          ],
        },
        {
          // The number an owner most often has not budgeted for.
          cells: ["Cash you must have", formatCurrency(cash.peakCashRequirement)],
          emphasis: true,
        },
        { cells: ["Deepest cash point", `Month ${cash.troughMonth}, ${formatCurrency(cash.troughAmount)}`] },
      ],
      note: "Cash you must have is the worst point of the ramp, including the deposit. It is usually well above the initial investment.",
    },
    {
      title: "What moves the outcome most",
      head: ["Lever", "20% worse", "20% better"],
      rows: result.sensitivity.map((entry) => ({
        cells: [
          entry.field,
          entry.paybackAtMinus20 === null ? "never" : `month ${entry.paybackAtMinus20}`,
          entry.paybackAtPlus20 === null ? "never" : `month ${entry.paybackAtPlus20}`,
        ],
      })),
      note: "Ranked by how much a 20% move in each direction shifts payback.",
    },
  ];

  if (result.warnings.length > 0) {
    tables.push({
      title: "Plausibility warnings",
      head: ["Severity", "Note"],
      rows: result.warnings.map((w) => ({ cells: [w.severity, w.message] })),
    });
  }

  /**
   * Derived, like the location summary — read off the result, never written.
   * The three things an owner has to know before signing anything: whether it
   * makes money, when it pays back, and how much cash it swallows first.
   */
  const trough = Math.min(...result.projection.map((m) => m.cash), 0);
  const summary = [
    steady.profit >= 0
      ? `At maturity this makes ${formatCurrency(steady.profit)} a month, a ` +
        `${formatPercent(steady.revenue > 0 ? steady.profit / steady.revenue : 0, 1)} margin on ` +
        `${formatCurrency(steady.revenue)} of revenue.`
      : `At maturity this LOSES ${formatCurrency(Math.abs(steady.profit))} a month on ` +
        `${formatCurrency(steady.revenue)} of revenue. The assumptions below do not support ` +
        `this business as configured.`,
    breakEven.paybackMonth === null
      ? `It does not pay back the ${formatCurrency(inputs.initialInvestment)} investment within ` +
        `24 months.`
      : `It pays back the ${formatCurrency(inputs.initialInvestment)} investment in month ` +
        `${breakEven.paybackMonth}` +
        (breakEven.paybackBandLow !== null && breakEven.paybackBandHigh !== null
          ? `, or between months ${breakEven.paybackBandLow} and ${breakEven.paybackBandHigh} ` +
            `once the ramp is allowed to run faster or slower.`
          : `.`),
    `The cash low point is ${formatCurrency(trough)}. That is the money you must have ` +
      `available before opening, and it is the figure most plans miss.`,
  ];

  return {
    kind: "scenario",
    title: `${category.label} financial projection`,
    subtitle: `${formatCurrency(inputs.monthlyRent)}/month rent · ${formatNumber(
      inputs.customersPerDay,
    )} customers/day · ${formatCurrency(inputs.avgPricePerTransaction)} average spend`,
    generatedOn: today(),
    summary,
    figures,
    tables,
    distanceBands: [],
    dimensionBars: [],
    ageBands: [],
    radarAxes: [],
    radarSeries: [],
    cashCurve: result.projection.map((m) => m.cash),
    mapDataUri: map.dataUri,
    mapNote: map.note,
    disclosures: [
      ...baseDisclosures(),
      "Category defaults are researched estimates of Malaysian F&B operating norms, " +
        "not figures measured at this site. Every one of them is editable in the simulator.",
    ],
    engineVersion: ENGINE_VERSION,
    presetVersion: PRESET_VERSION,
  };
}

// ---------------------------------------------------------------- location

export interface LocationReportInput {
  point: LatLng;
  label: string;
  category: BusinessCategory;
  radiusMetres: number;
  competitors: CompetitorSummary;
  truncated: boolean;
  completeToMetres: number | null;
  density: DensityBand[];
  demographics: { district: string; state: string; total: number; age: Record<string, number> } | null;
  rentOverride: number | null;
  /**
   * Residents within the radius, from the 400m grid. Filled by the route from
   * the server's own data, never taken from the request body — it is a
   * measurement, and the client has no business asserting it.
   */
  catchment?: number | null;
  /**
   * The outlets themselves, for the "who is already there" table.
   *
   * An INPUT, at the same trust level as the summary beside it: the server
   * cannot re-derive this without a paid Places call, so it is accepted,
   * capped and sanitised — never used to compute anything scored.
   */
  rivals?: CompetitorWithDistance[];
}

/** Shared by the location and comparison reports so one score is scored one way. */
function scoreOne(input: LocationReportInput): {
  score: LocationScore;
  rentLine: string;
  rent: ResolvedRent | null;
  sensitivity: RentSensitivity | null;
} {
  const rent = resolveRent(
    input.point,
    input.category,
    input.rentOverride && input.rentOverride > 0 ? { monthlyRent: input.rentOverride } : undefined,
  );

  const score = scoreLocation({
    competitors: input.competitors,
    truncated: input.truncated,
    completeToMetres: input.completeToMetres,
    radiusMetres: input.radiusMetres,
    demographics: input.demographics,
    catchment: input.catchment ?? null,
    rent,
    category: input.category,
    point: input.point,
  });

  const rentLine = rent
    ? `${formatCurrency(rent.monthlyRent)}/month${
        rent.kind === "proxy" && rent.district
          ? `, inferred from the ${rent.district.label} benchmark, ${formatNumber(
              rent.distanceMetres ?? 0,
            )}m away, reviewed ${rent.reviewed}`
          : ", the figure you supplied"
      }. Break-even ${rentSensitivity(rent, input.category, input.point).breakEvenPerDay ?? "not scored"}/day.`
    : "No rent benchmark covers this location, so rent is excluded from the score rather than guessed.";

  return { score, rentLine, rent, sensitivity: rent ? rentSensitivity(rent, input.category, input.point) : null };
}

const KIND_WORD = { direct: "measured", proxy: "inferred", unavailable: "no data" } as const;

/** Words, not colours — a PDF gets printed in black and white. */
const RENT_LIGHT = {
  green: "Comfortable",
  amber: "Tight",
  red: "Very exposed",
} as const;

/**
 * Distance rings, correctly labelled and correctly qualified.
 *
 * `densityByBand` returns EXCLUSIVE rings — 0-250, 250-500, 500-1000 — and the
 * report used to label them "within 250m / 500m / 1000m". That made it print
 * "0 outlets within 500m" directly beneath "20 within 250m", which is both a
 * contradiction and not what the number means.
 *
 * The second correction matters more. Places returns the nearest 20 and stops,
 * so any ring starting beyond `completeToMetres` was never searched. Printing
 * "0" there states a measurement we do not have. The screen already says "not
 * searched"; this makes the PDF agree with it.
 */
export function distanceBars(
  density: DensityBand[],
  completeToMetres: number | null,
): DistanceBand[] {
  let lower = 0;

  return density.map((band) => {
    const from = lower;
    lower = band.upToMetres;

    return {
      label: `${formatNumber(from)}-${formatNumber(band.upToMetres)}m`,
      value: band.count,
      unsearched: completeToMetres !== null && from >= completeToMetres,
    };
  });
}

/**
 * The short version — read off the score, not written about it.
 *
 * Says only what the object supports: where the site is strong, where it is
 * weak, which constraint binds, and how much could not be measured. When the
 * profile is flat it says so rather than inventing a strongest axis, the same
 * restraint /compare shows when it declines to call a 5-point gap.
 */
export function deriveSummary(
  score: LocationScore,
  input: { truncated: boolean; completeToMetres: number | null; competitors: CompetitorSummary },
): string[] {
  const scored = score.dimensions.filter((d) => d.kind !== "unavailable");
  const missing = score.dimensions.filter((d) => d.kind === "unavailable");
  const lines: string[] = [];

  const band =
    score.overall >= 70 ? "strong" : score.overall >= 40 ? "mixed" : "difficult";
  lines.push(
    `This location scores ${Math.round(score.overall)} out of 100, a ${band} profile. ` +
      `with ${formatPercent(score.completeness, 0)} of the assessment based on measured data.`,
  );

  if (scored.length >= 2) {
    const sorted = [...scored].sort((a, b) => b.score - a.score);
    const best = sorted[0]!;
    const worst = sorted[sorted.length - 1]!;

    if (best.score - worst.score < 10) {
      lines.push(
        `No single dimension stands out: the ${scored.length} measured axes sit within ` +
          `${Math.round(best.score - worst.score)} points of each other, so there is no one ` +
          `factor to fix or to lean on.`,
      );
    } else {
      lines.push(
        `Strongest on ${best.label.toLowerCase()} (${Math.round(best.score)}) and weakest on ` +
          `${worst.label.toLowerCase()} (${Math.round(worst.score)}). ` +
          `${worst.label} is the binding constraint here. It is what would have to change for ` +
          `this site to score better, and it is where to concentrate the questions you ask next.`,
      );
    }
  }

  if (input.truncated) {
    lines.push(
      `Competitor counts are a floor, not a total: the search returned the nearest ` +
        `${formatNumber(input.competitors.total)} and stopped` +
        (input.completeToMetres
          ? ` about ${formatNumber(input.completeToMetres)}m out. Anything beyond that was not ` +
            `searched, so treat the outer rings as unknown rather than empty.`
          : `. Treat the outer rings as unknown rather than empty.`),
    );
  }

  if (missing.length > 0) {
    lines.push(
      `${missing.length} of ${score.dimensions.length} dimensions could not be measured here ` +
        `(${missing.map((d) => d.label.toLowerCase()).join(", ")}). They are excluded from the ` +
        `score rather than counted as zero, so the figure above describes what is known.`,
    );
  }

  return lines;
}

export function buildLocationReport(
  input: LocationReportInput,
  map: { dataUri: string | null; note: string | null } = { dataUri: null, note: null },
): ReportModel {
  const { score, rentLine, rent, sensitivity } = scoreOne(input);
  const category = CATEGORY_PRESETS[input.category];
  const bands = distanceBars(input.density, input.completeToMetres);

  const figures: Figure[] = [
    {
      label: "Success score",
      value: `${Math.round(score.overall)} / 100`,
      note: `${formatPercent(score.completeness, 0)} of the profile measured`,
    },
    {
      label: "Competitors",
      value: `${input.truncated ? "20+" : formatNumber(input.competitors.total)}`,
      note: `within ${formatNumber(input.radiusMetres)}m`,
    },
    {
      label: "Average rating",
      value: input.competitors.averageRating === null ? "unrated" : String(input.competitors.averageRating),
      note: `${formatNumber(input.competitors.ratedCount)} rated`,
    },
    {
      label: "Nearest rival",
      value:
        input.competitors.nearestMetres === null
          ? "none found"
          : `${formatNumber(input.competitors.nearestMetres)}m`,
    },
  ];

  const tables: Table[] = [
    {
      title: "Score breakdown",
      head: ["Dimension", "Score", "Basis", "Weight", "What it means"],
      rows: score.dimensions.map((d) => ({
        cells: [
          d.label,
          d.kind === "unavailable" ? "not scored" : String(Math.round(d.score)),
          KIND_WORD[d.kind],
          d.weight > 0 ? formatPercent(d.weight, 0) : "excluded",
          d.note,
        ],
      })),
      note: "Weights reflect how far each signal can be trusted, not how much each factor matters to a real business. They renormalise over the dimensions actually available.",
    },
    {
      title: "Competition by distance",
      head: ["Ring", "Outlets"],
      // Rings, not "within Xm". densityByBand returns exclusive bands, so the
      // old cumulative-sounding label printed "0 within 500m" beneath "20
      // within 250m" — a contradiction, and not what the number meant.
      rows: bands.map((band) => ({
        cells: [band.label, band.unsearched ? "not searched" : formatNumber(band.value)],
      })),
      ...(input.truncated
        ? {
            note:
              "The search returned the nearest 20 and stopped" +
              (input.completeToMetres
                ? `, complete only to about ${formatNumber(input.completeToMetres)}m. Rings beyond that are marked "not searched" rather than shown as zero. They are not empty, they are unknown.`
                : ". Counts are a floor, not a total."),
          }
        : {}),
    },
    // Only when there is no rent to break down. Where a benchmark or a quoted
    // figure exists, the "Rent and break-even" table below supersedes this and
    // printing both said the same thing twice on one page.
    ...(rent ? [] : [{ title: "Rent", head: ["Assessment"], rows: [{ cells: [rentLine] }] }]),
  ];

  /**
   * Who is actually there. The summary says "20 outlets, 4.2 average"; this
   * says which twenty, so a reader can recognise the street.
   */
  const rivals = (input.rivals ?? []).slice(0, 12);
  if (rivals.length > 0) {
    tables.push({
      title: "Who is already there",
      head: ["Outlet", "Rating", "Reviews", "Distance"],
      rows: rivals.map((rival) => ({
        cells: [
          rival.name,
          rival.rating === null ? "unrated" : String(rival.rating),
          formatNumber(rival.reviewCount),
          `${formatNumber(rival.distanceMetres)}m`,
        ],
      })),
      note:
        `Nearest ${formatNumber(rivals.length)} of ${
          input.truncated ? "at least " : ""
        }${formatNumber(input.competitors.total)} found, ordered by distance. ` +
        "Ratings and review counts are Google's, captured when this report was generated.",
    });
  }

  if (typeof input.catchment === "number" && input.catchment > 0) {
    const percentile = Math.round(catchmentPercentile(input.catchment, input.radiusMetres) * 100);
    tables.push({
      title: "Catchment",
      head: ["Measure", "Value"],
      rows: [
        {
          cells: [
            `Residents within ${formatNumber(input.radiusMetres)}m`,
            formatNumber(Math.round(input.catchment)),
          ],
          emphasis: true,
        },
        { cells: ["Compared nationally", `Denser than ${percentile}% of where Malaysians live`] },
      ],
      // The figure this table exists to replace.
      note:
        "Measured from a 400m population grid and area-weighted, so it is a real walk-in " +
        "catchment rather than a district total. This is the population figure to use; the " +
        "district population below is context for the mix only.",
    });
  }

  if (rent && sensitivity) {
    tables.push({
      title: "Rent and break-even",
      head: ["Measure", "Value"],
      rows: [
        { cells: ["Monthly rent", formatCurrency(rent.monthlyRent)], emphasis: true },
        ...(rent.psf !== null
          ? [{ cells: ["Per square foot", `RM${rent.psf}/sqft`] }]
          : []),
        {
          cells: [
            "Customers per day to break even",
            sensitivity.breakEvenPerDay === null
              ? "Unreachable at any volume"
              : formatNumber(sensitivity.breakEvenPerDay),
          ],
          emphasis: true,
        },
        { cells: ["Exposure", RENT_LIGHT[sensitivity.light]] },
        {
          cells: [
            "Basis",
            rent.kind === "direct"
              ? "The rent you supplied"
              : `${rent.district?.label ?? "Nearest"} benchmark, ${formatNumber(
                  rent.distanceMetres ?? 0,
                )}m away, reviewed ${rent.reviewed}`,
          ],
        },
      ],
      note:
        "Break-even covers ALL fixed costs, not rent alone. Nobody breaks even on rent by " +
        "itself. Every other fixed cost is a category constant, so between two sites the whole " +
        "difference is the rent. " +
        sensitivity.note,
    });
  }

  if (input.demographics) {
    const working = [
      "15-19", "20-24", "25-29", "30-34", "35-39",
      "40-44", "45-49", "50-54", "55-59", "60-64",
    ].reduce((sum, band) => sum + (input.demographics?.age[band] ?? 0), 0);

    tables.push({
      title: "Area demographics",
      head: ["Measure", "Value"],
      rows: [
        {
          cells: [
            "District",
            // The federal territories are their own state, so naming both
            // prints "W.P. Kuala Lumpur, W.P. Kuala Lumpur" - which reads as
            // a bug rather than as geography.
            input.demographics.state && input.demographics.state !== input.demographics.district
              ? `${input.demographics.district}, ${input.demographics.state}`
              : input.demographics.district,
          ],
        },
        { cells: ["District population", formatNumber(Math.round(input.demographics.total))] },
        {
          cells: [
            "Working age (15-64)",
            `${formatNumber(Math.round(working))} (${formatPercent(
              input.demographics.total > 0 ? working / input.demographics.total : 0,
              0,
            )})`,
          ],
        },
      ],
      // The error this table most invites, stated where the number is.
      note: "This is the whole administrative district, which is far larger than a walk-in catchment. It is context for the mix, never a customer count.",
    });
  }

  const AGE_ORDER = [
    "0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44",
    "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+",
  ];

  return {
    kind: "location",
    title: input.label.slice(0, 120),
    subtitle: `${category.label} · ${formatNumber(input.radiusMetres)}m radius · ${input.point.lat.toFixed(
      5,
    )}, ${input.point.lng.toFixed(5)}`,
    generatedOn: today(),
    summary: deriveSummary(score, input),
    figures,
    tables,
    distanceBands: bands,
    dimensionBars: score.dimensions.map((d) => ({
      label: d.label,
      score: d.kind === "unavailable" ? null : d.score,
      basis: KIND_WORD[d.kind],
    })),
    ageBands: input.demographics
      ? AGE_ORDER.filter((band) => (input.demographics?.age[band] ?? 0) > 0).map((band) => ({
          label: band,
          value: input.demographics?.age[band] ?? 0,
        }))
      : [],
    radarAxes: score.dimensions.map((d) => d.label),
    radarSeries: [
      {
        label: input.label.slice(0, 60),
        values: score.dimensions.map((d) => (d.kind === "unavailable" ? 0 : d.score)),
        missing: score.dimensions.map((d) => d.kind === "unavailable"),
      },
    ],
    cashCurve: [],
    mapDataUri: map.dataUri,
    mapNote: map.note,
    disclosures: [
      ...baseDisclosures(),
      "The success score is a comparison aid, not a forecast. A number on its own means " +
        "little; the point is the difference between two sites.",
      "Competitor data comes from Google Places, which returns at most 20 results ranked by " +
        "distance. Where that cap was hit, counts are a floor.",
      "Rent benchmarks are researched estimates for ground-floor F&B, not transacted rents. " +
        "Malaysia does not publish transacted retail rents in machine-readable form.",
    ],
    engineVersion: ENGINE_VERSION,
    presetVersion: PRESET_VERSION,
  };
}

// -------------------------------------------------------------- comparison

export function buildComparisonReport(
  category: BusinessCategory,
  radiusMetres: number,
  inputs: LocationReportInput[],
  map: { dataUri: string | null; note: string | null } = { dataUri: null, note: null },
): ReportModel {
  const scored: ComparedLocation[] = inputs.map((input) => ({
    id: `${input.point.lat},${input.point.lng}`,
    label: input.label.slice(0, 60),
    score: scoreOne(input).score,
  }));

  const comparison: Comparison = compareLocations(scored);
  const axes = scored[0]?.score.dimensions.map((d) => d.label) ?? [];

  const winner = comparison.winnerId
    ? scored.find((s) => s.id === comparison.winnerId)?.label
    : null;

  const figures: Figure[] = scored.map((s) => ({
    label: s.label,
    value: String(Math.round(s.score.overall)),
    ...(comparison.winnerId === s.id ? { note: "highest" } : {}),
  }));

  const tables: Table[] = [
    {
      title: "Dimension by dimension",
      head: ["Dimension", ...scored.map((s) => s.label), "Verdict"],
      rows: comparison.dimensions.map((dimension) => {
        // Extracted so the union narrows once; repeated property access on
        // `dimension.outcome` loses it.
        const outcome = dimension.outcome;
        const verdict =
          outcome.kind === "winner"
            ? (scored.find((s) => s.id === outcome.winnerId)?.label ?? "")
            : outcome.kind === "tooClose"
              ? "too close to call"
              : "no data either side";

        return {
          cells: [
            dimension.label,
            ...dimension.scores.map((cell) =>
              // Null, never zero: "no data" and "scored zero" are different claims.
              cell.score === null ? "not scored" : String(Math.round(cell.score)),
            ),
            verdict,
          ],
        };
      }),
    },
    {
      title: "Overall",
      head: ["Location", "Score", "Basis"],
      rows: scored.map((s) => ({
        cells: [
          s.label,
          String(Math.round(s.score.overall)),
          `${formatPercent(s.score.completeness, 0)} of the profile measured`,
        ],
        emphasis: comparison.winnerId === s.id,
      })),
      note: winner
        ? `${winner} scores highest, by ${formatNumber(comparison.overallSpread, 1)} points.`
        : "Too close to call. The difference is inside the margin these figures can support.",
    },
  ];

  /**
   * Derived. Declines to name a winner when the spread is inside what these
   * figures can support, exactly as the comparison page does — a report that
   * picks a site on a two-point gap is worse than one that says it cannot.
   */
  const decisive = comparison.dimensions
    .filter((d) => d.outcome.kind === "winner")
    .sort(
      (a, b) =>
        Math.abs((b.outcome as { spread: number }).spread) -
        Math.abs((a.outcome as { spread: number }).spread),
    )[0];

  const summary = [
    winner
      ? `${winner} scores highest, by ${formatNumber(comparison.overallSpread, 1)} points across ` +
        `${scored.length} locations compared on the same category and the same radius.`
      : `No location wins. The spread across ${scored.length} sites is ` +
        `${formatNumber(comparison.overallSpread, 1)} points, which is inside what these figures ` +
        `can support, so treat them as equivalent on the evidence here.`,
    ...(decisive
      ? [
          `The difference is driven mostly by ${decisive.label.toLowerCase()}, where the gap is ` +
            `${formatNumber(
              Math.abs((decisive.outcome as { spread: number }).spread),
              1,
            )} points. Dimensions marked "too close" below did not separate the sites at all.`,
        ]
      : []),
  ];

  return {
    kind: "comparison",
    title: `${scored.map((s) => s.label).join(" vs ")}`,
    subtitle: `${CATEGORY_PRESETS[category].label} · ${formatNumber(
      radiusMetres,
    )}m radius · same category and radius for every location`,
    generatedOn: today(),
    summary,
    figures,
    tables,
    distanceBands: [],
    dimensionBars: [],
    ageBands: [],
    radarAxes: axes,
    radarSeries: scored.map((s) => ({
      label: s.label,
      values: s.score.dimensions.map((d) => (d.kind === "unavailable" ? 0 : d.score)),
      missing: s.score.dimensions.map((d) => d.kind === "unavailable"),
    })),
    cashCurve: [],
    mapDataUri: map.dataUri,
    mapNote: map.note,
    disclosures: [
      ...baseDisclosures(),
      "Every location here was searched with the same business category and the same radius. " +
        "Comparing different settings would produce numbers that cannot be ranked against each other.",
      "Dimensions within a few points are reported as too close to call rather than crowned, " +
        "and a dimension with no data on either side is never shown as a tie.",
    ],
    engineVersion: ENGINE_VERSION,
    presetVersion: PRESET_VERSION,
  };
}
