import type { LocationScore } from "@spotential/sim-engine";

/**
 * One sentence naming the strongest and weakest axis.
 *
 * DERIVED, NOT WRITTEN, and deliberately not generated by Gemini. It sits
 * directly above the same dimension table it summarises, so a model phrasing
 * it could produce a line that disagrees with the numbers beside it — the one
 * failure the whole product is built to avoid. This reads the score object and
 * names what it finds.
 */
export function Verdict({ score }: { score: LocationScore }) {
  const scored = score.dimensions.filter((d) => d.kind !== "unavailable");

  if (scored.length < 2) {
    return (
      <p className="hero-verdict">
        Not enough measured yet to say much. The dimensions below show what is missing.
      </p>
    );
  }

  const sorted = [...scored].sort((a, b) => b.score - a.score);
  const best = sorted[0]!;
  const worst = sorted[sorted.length - 1]!;
  const missing = score.dimensions.filter((d) => d.kind === "unavailable");

  // Within a few points there is no strongest or weakest to name, and
  // pretending otherwise is the same false precision the comparison page
  // refuses when it says "too close to call".
  const flat = best.score - worst.score < 10;

  return (
    <p className="hero-verdict">
      {flat ? (
        <>
          No dimension stands out here. The profile is even across{" "}
          <strong>{scored.length}</strong> measured axes.
        </>
      ) : (
        <>
          Strongest on <strong>{best.label.toLowerCase()}</strong>, weakest on{" "}
          <strong>{worst.label.toLowerCase()}</strong>.
        </>
      )}{" "}
      {missing.length > 0 && (
        <>
          {missing.length} of {score.dimensions.length} dimensions could not be measured here.
        </>
      )}
    </p>
  );
}
